apiVersion: v1
kind: Secret
metadata:
  name: azure-monitor-secrets
data:
  # The values below need to be base64 encoded
  # Use 'echo -n "<value>" | base64' to encode the values
  activeDirectoryClientId: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  activeDirectoryClientPassword: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-monitor-trigger-auth
spec:
  secretTargetRef:
    - parameter: activeDirectoryClientId
      name: azure-monitor-secrets
      key: activeDirectoryClientId
    - parameter: activeDirectoryClientPassword
      name: azure-monitor-secrets
      key: activeDirectoryClientPassword
---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: azure-monitor-scaler
spec:
  minReplicaCount: 0
  maxReplicaCount: 2
  jobTargetRef:
    template:
      spec:
        containers:
        - name: gojob
          image: gojob:latest
          imagePullPolicy: IfNotPresent
        restartPolicy: Never
  triggers:
  - type: azure-monitor
    metadata:
      # Change resourceURI to fit the target resource
      resourceURI: Microsoft.App/jobs/some-job
      tenantId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      subscriptionId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      resourceGroupName: some-rg
      # Change metricName to ones supported under the target resource
      metricName: Executions
      metricAggregationType: Average
      targetValue: "1"
    authenticationRef:
      name: azure-monitor-trigger-auth

